"""LinkGraph — the wiki's knowledge graph, built at index time.

Extracts [[wikilinks]] from every Markdown note in the vault (all layers)
and persists them as an edge table in a stdlib SQLite database at
`.llmwiki/graph.db`. Zero external dependencies.

The graph answers the questions a memory system actually needs:
  - neighbors(path)   — what does this note link to? (forward traversal)
  - backlinks(path)   — which notes reference this one? (reverse traversal)
  - dead_links()      — links pointing at notes that don't exist
  - orphans()         — notes nothing links to

Edges are stored resolved (target = vault-relative path) when the link can
be mapped to a file, or unresolved (resolved = 0) otherwise — dead links are
data, not silent failures.

Supports Obsidian link syntax: [[Note]], [[Note|alias]], [[Note#section]].
"""

from __future__ import annotations

import logging
import re
import sqlite3
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)

_WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


class LinkGraph:
    """Persistent wikilink edge table for a vault."""

    def __init__(self, vault_path: Path, db_name: str = ".llmwiki/graph.db"):
        self.vault_path = Path(vault_path)
        self.db_name = db_name
        self._conn: Optional[sqlite3.Connection] = None

    # ------------------------------------------------------------------
    # Storage
    # ------------------------------------------------------------------

    def _connect(self) -> sqlite3.Connection:
        if self._conn is None:
            db_path = self.vault_path / self.db_name
            db_path.parent.mkdir(parents=True, exist_ok=True)
            self._conn = sqlite3.connect(str(db_path))
            self._conn.row_factory = sqlite3.Row
            self._conn.execute(
                "CREATE TABLE IF NOT EXISTS files (" "  path TEXT PRIMARY KEY," "  mtime REAL" ")"
            )
            self._conn.execute(
                "CREATE TABLE IF NOT EXISTS edges ("
                "  source TEXT,"
                "  target TEXT,"
                "  resolved INTEGER,"
                "  UNIQUE(source, target)"
                ")"
            )
            self._conn.execute("CREATE INDEX IF NOT EXISTS idx_edges_source ON edges(source)")
            self._conn.execute("CREATE INDEX IF NOT EXISTS idx_edges_target ON edges(target)")
            self._conn.commit()
        return self._conn

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    # ------------------------------------------------------------------
    # Scanning
    # ------------------------------------------------------------------

    def _scan_files(self) -> Dict[str, float]:
        """All vault Markdown files as {relative_path: mtime}."""
        files: Dict[str, float] = {}
        for md in self.vault_path.rglob("*.md"):
            # Skip hidden dirs (.llmwiki, .obsidian, .git, ...)
            rel = md.relative_to(self.vault_path)
            if any(part.startswith(".") for part in rel.parts):
                continue
            # Skip vault scaffolding generated by `llmwiki init`
            if rel.name == "SCHEMA.md" and rel.parent == Path("."):
                continue
            try:
                files[rel.as_posix()] = md.stat().st_mtime
            except OSError:
                continue
        return files

    @staticmethod
    def _stem_variants(name: str) -> Set[str]:
        """Normalized lookup keys for a note name or filename stem."""
        variants = {name, name.lower()}
        for a, b in ((" ", "-"), (" ", "_"), ("-", " "), ("_", " ")):
            variants.add(name.replace(a, b))
            variants.add(name.replace(a, b).lower())
        return variants

    def _build_stem_index(self, files: Dict[str, float]) -> Dict[str, str]:
        """Map every stem variant → relative path. First registration wins."""
        index: Dict[str, str] = {}
        for rel in files:
            stem = Path(rel).stem
            for variant in self._stem_variants(stem):
                index.setdefault(variant, rel)
        return index

    @staticmethod
    def _extract_links(text: str) -> List[str]:
        """Raw link targets from note text, normalized (alias/heading stripped)."""
        links = []
        for m in _WIKILINK_RE.finditer(text):
            target = m.group(1).split("|", 1)[0].split("#", 1)[0].strip()
            if target:
                links.append(target)
        return links

    def _resolve(self, link_name: str, stem_index: Dict[str, str]) -> Optional[str]:
        for variant in self._stem_variants(link_name):
            if variant in stem_index:
                return stem_index[variant]
        return None

    def _replace_edges(
        self,
        conn: sqlite3.Connection,
        source: str,
        links: List[str],
        stem_index: Dict[str, str],
    ) -> None:
        conn.execute("DELETE FROM edges WHERE source = ?", (source,))
        for link in links:
            target = self._resolve(link, stem_index)
            if target == source:
                continue  # self-link
            conn.execute(
                "INSERT OR IGNORE INTO edges (source, target, resolved) VALUES (?, ?, ?)",
                (source, target if target else link, 1 if target else 0),
            )

    # ------------------------------------------------------------------
    # Build / update
    # ------------------------------------------------------------------

    def rebuild(self) -> Dict[str, int]:
        """Full rebuild of the edge table. Returns stats."""
        conn = self._connect()
        files = self._scan_files()
        stem_index = self._build_stem_index(files)

        conn.execute("DELETE FROM edges")
        conn.execute("DELETE FROM files")

        edge_count = 0
        for rel, mtime in files.items():
            conn.execute(
                "INSERT OR REPLACE INTO files (path, mtime) VALUES (?, ?)",
                (rel, mtime),
            )
            try:
                text = (self.vault_path / rel).read_text(encoding="utf-8")
            except Exception:
                continue
            links = self._extract_links(text)
            self._replace_edges(conn, rel, links, stem_index)
            edge_count += len(links)

        conn.commit()
        stats = {"notes": len(files), "links": edge_count}
        logger.info("LinkGraph rebuilt: %s", stats)
        return stats

    def update_incremental(self) -> int:
        """Re-extract edges only for files changed since the last run.

        Returns the number of files re-processed.
        """
        conn = self._connect()
        current = self._scan_files()
        known = {row["path"]: row["mtime"] for row in conn.execute("SELECT path, mtime FROM files")}

        changed = [rel for rel, mtime in current.items() if rel not in known or mtime > known[rel]]
        removed = [rel for rel in known if rel not in current]

        if not changed and not removed:
            return 0

        stem_index = self._build_stem_index(current)

        for rel in changed:
            conn.execute(
                "INSERT OR REPLACE INTO files (path, mtime) VALUES (?, ?)",
                (rel, current[rel]),
            )
            try:
                text = (self.vault_path / rel).read_text(encoding="utf-8")
            except Exception:
                continue
            self._replace_edges(conn, rel, self._extract_links(text), stem_index)

        for rel in removed:
            conn.execute("DELETE FROM files WHERE path = ?", (rel,))
            conn.execute("DELETE FROM edges WHERE source = ?", (rel,))
            # Inbound edges to a deleted note become dead links
            conn.execute("UPDATE edges SET resolved = 0 WHERE target = ?", (rel,))

        # Edges that were dead may now resolve (a target note was created)
        if changed:
            dead = conn.execute("SELECT DISTINCT target FROM edges WHERE resolved = 0").fetchall()
            for row in dead:
                target = self._resolve(row["target"], stem_index)
                if target:
                    conn.execute(
                        "UPDATE edges SET target = ?, resolved = 1 "
                        "WHERE target = ? AND resolved = 0",
                        (target, row["target"]),
                    )

        conn.commit()
        logger.debug(
            "LinkGraph incremental update: %d changed, %d removed", len(changed), len(removed)
        )
        return len(changed) + len(removed)

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def neighbors(self, path: str) -> List[str]:
        """Resolved forward links from a note, in insertion order."""
        conn = self._connect()
        rows = conn.execute(
            "SELECT target FROM edges WHERE source = ? AND resolved = 1",
            (path,),
        ).fetchall()
        return [r["target"] for r in rows]

    def backlinks(self, path: str) -> List[str]:
        """Notes that link to this note."""
        conn = self._connect()
        rows = conn.execute(
            "SELECT source FROM edges WHERE target = ? AND resolved = 1",
            (path,),
        ).fetchall()
        return [r["source"] for r in rows]

    def neighborhood(self, path: str, hops: int = 2) -> Dict[str, float]:
        """Weighted BFS around a note.

        Returns {path: weight} with hop-1 forward = 1.0, backlinks = 0.8,
        hop-2 forward = 0.5. The seed itself is excluded.
        """
        result: Dict[str, float] = {}

        for target in self.neighbors(path):
            if target != path:
                result[target] = max(result.get(target, 0.0), 1.0)
        for source in self.backlinks(path):
            if source != path:
                result[source] = max(result.get(source, 0.0), 0.8)

        if hops >= 2:
            for hop1 in list(result):
                if result[hop1] < 1.0:
                    continue  # only expand forward links
                for target in self.neighbors(hop1):
                    if target != path and target not in result:
                        result[target] = 0.5

        return result

    def dead_links(self) -> List[Tuple[str, str]]:
        """Unresolved links as (source, target_name) pairs."""
        conn = self._connect()
        rows = conn.execute(
            "SELECT source, target FROM edges WHERE resolved = 0 ORDER BY source"
        ).fetchall()
        return [(r["source"], r["target"]) for r in rows]

    def orphans(self, dirs: Optional[List[str]] = None) -> List[str]:
        """Notes with no inbound links.

        Args:
            dirs: Restrict to these top-level directories (e.g. the compiled
                layer). Daily/raw notes are typically unlinked by design, so
                health checks usually pass the compiled dirs here.
        """
        conn = self._connect()
        rows = conn.execute(
            "SELECT path FROM files WHERE path NOT IN "
            "(SELECT DISTINCT target FROM edges WHERE resolved = 1) "
            "ORDER BY path"
        ).fetchall()
        paths = [r["path"] for r in rows]
        if dirs:
            prefixes = tuple(d.rstrip("/") + "/" for d in dirs)
            paths = [p for p in paths if p.startswith(prefixes)]
        return paths

    def resolve(self, link_name: str) -> Optional[str]:
        """Resolve a link name to a vault-relative path, or None."""
        conn = self._connect()
        files = {row["path"]: row["mtime"] for row in conn.execute("SELECT path, mtime FROM files")}
        stem_index = self._build_stem_index(files)
        return self._resolve(link_name, stem_index)

    def stats(self) -> Dict[str, int]:
        conn = self._connect()
        notes = conn.execute("SELECT COUNT(*) AS c FROM files").fetchone()["c"]
        edges = conn.execute("SELECT COUNT(*) AS c FROM edges WHERE resolved = 1").fetchone()["c"]
        dead = conn.execute("SELECT COUNT(*) AS c FROM edges WHERE resolved = 0").fetchone()["c"]
        return {"notes": notes, "edges": edges, "dead_links": dead}
